# Generated by Django 2.0.5 on 2018-07-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='doctor_image')),
                ('profile_name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs'), ('Ir.', 'Ir'), ('Dr.', 'Dr'), ('Drs', 'Drs'), ('Professor', 'Professor')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_day', models.DateField()),
                ('phone', models.IntegerField()),
                ('qualification', models.TextField()),
                ('interest', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='patient_image')),
                ('profile_name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs'), ('Ir.', 'Ir'), ('Dr.', 'Dr'), ('Drs', 'Drs'), ('Professor', 'Professor')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_day', models.DateField()),
                ('phone', models.IntegerField()),
                ('prescription', models.TextField()),
                ('interest', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PresentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='disease.Diseases')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='medicine.Medicinary')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='userinfo.Patient')),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='disease.Symptoms')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_image', models.ImageField(blank=True, upload_to='research_image')),
                ('details', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='userinfo.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division'),
        ),
    ]
