# Generated by Django 2.0.5 on 2018-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinary',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicinary',
            name='symptoms',
            field=models.ManyToManyField(related_name='medicines', to='disease.Symptoms'),
        ),
    ]
