# Generated by Django 2.0 on 2018-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20180723_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinewisesymptom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
